# Generated by Django 5.1.1 on 2024-11-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_name_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles_img/default.jpg', null=True, upload_to='profiles_img/'),
        ),
    ]
