# Generated by Django 5.1.1 on 2024-12-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_channel_art',
            field=models.ImageField(blank=True, default='profiles_channel_art/default.jpg', null=True, upload_to='profiles_channel_art/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
