# Generated by Django 5.1 on 2024-09-02 16:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('question', models.TextField(blank=True, null=True)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_image', models.ImageField(blank=True, null=True, upload_to='answer_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_rate', models.CharField(choices=[('Easy', 'Easy Rate'), ('Good', 'Good Rate'), ('Hard', 'Hard Rate'), ('Again', 'Again Rate')], max_length=200)),
                ('interval', models.IntegerField()),
                ('repetition_count', models.IntegerField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decks.flashcard')),
            ],
        ),
    ]
