# Generated by Django 5.1.1 on 2024-10-27 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_flashcard_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewhistory',
            old_name='interval',
            new_name='interval_day',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reviewhistory',
            name='repetition_count',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='difficulty',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval_day',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reviewhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ReviewSchedule',
        ),
    ]
