# Generated by Django 5.1.1 on 2024-10-16 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_parent_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='answer_image',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question_image',
        ),
        migrations.CreateModel(
            name='CardSide',
            fields=[
                ('side', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], max_length=5)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveBigIntegerField()),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='decks.flashcard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CardContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], max_length=5)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images/')),
                ('order', models.PositiveIntegerField()),
                ('card_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='decks.cardside')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
