# Generated by Django 5.1.1 on 2024-11-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_rename_interval_reviewhistory_interval_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
