# Generated by Django 5.1.1 on 2024-11-16 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_deck_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_image',
            field=models.ImageField(blank=True, default='deck_images/testdeck.jpg', null=True, upload_to='deck_images'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('decks', models.ManyToManyField(blank=True, related_name='categories', to='decks.deck')),
            ],
        ),
    ]
