# Generated by Django 5.1.1 on 2024-10-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0006_deck_deck_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardcontent',
            options={'ordering': ['-side', 'order']},
        ),
        migrations.AlterField(
            model_name='cardcontent',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='decks.flashcard'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_image',
            field=models.ImageField(blank=True, default='default.svg', null=True, upload_to='deck_images'),
        ),
    ]
