# Generated by Django 5.1.1 on 2024-11-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_category_owner_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardContent',
        ),
    ]
