# Generated by Django 5.1.1 on 2024-10-25 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0008_deck_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_day', models.PositiveIntegerField(default=1)),
                ('repetition_count', models.PositiveBigIntegerField(default=0)),
                ('difficulty', models.FloatField(default=2.5)),
                ('flshcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='decks.flashcard')),
            ],
        ),
    ]
