# Generated by Django 5.1.1 on 2024-11-22 18:17

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_flashcard_back_flashcard_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='back',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='front',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images'),
        ),
        migrations.CreateModel(
            name='DeckImage',
            fields=[
                ('image', models.ImageField(upload_to='flashcard_images/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='decks.deck')),
            ],
        ),
    ]
