# Generated by Django 5.1.1 on 2024-11-22 19:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_alter_deckimage_id_alter_deckimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
