# Generated by Django 5.1.1 on 2024-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0012_alter_deckimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
