# Generated by Django 5.1.1 on 2024-11-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0013_alter_deckimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='deck_image',
        ),
    ]
